// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ4gL7l5HbDPoAnBVXaZoBNhpaC3fzbVw',
    appId: '1:895099598891:android:a5175d06b9fd37b282926e',
    messagingSenderId: '895099598891',
    projectId: 'inventory-management-48093',
    storageBucket: 'inventory-management-48093.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYKObhXo8qi89g1_W-J1XyXaMnOvxevCs',
    appId: '1:895099598891:web:d638a94583684a7382926e',
    messagingSenderId: '895099598891',
    projectId: 'inventory-management-48093',
    authDomain: 'inventory-management-48093.firebaseapp.com',
    storageBucket: 'inventory-management-48093.firebasestorage.app',
    measurementId: 'G-7K5CHKJQ1H',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHRA6nGVn-X71wGJKg7lTntzc_Qxy25Ps',
    appId: '1:895099598891:ios:cc59e4e48b09588882926e',
    messagingSenderId: '895099598891',
    projectId: 'inventory-management-48093',
    storageBucket: 'inventory-management-48093.firebasestorage.app',
    iosBundleId: 'com.example.inClassInventoryManagement',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHRA6nGVn-X71wGJKg7lTntzc_Qxy25Ps',
    appId: '1:895099598891:ios:cc59e4e48b09588882926e',
    messagingSenderId: '895099598891',
    projectId: 'inventory-management-48093',
    storageBucket: 'inventory-management-48093.firebasestorage.app',
    iosBundleId: 'com.example.inClassInventoryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYKObhXo8qi89g1_W-J1XyXaMnOvxevCs',
    appId: '1:895099598891:web:0d03f78daa82623882926e',
    messagingSenderId: '895099598891',
    projectId: 'inventory-management-48093',
    authDomain: 'inventory-management-48093.firebaseapp.com',
    storageBucket: 'inventory-management-48093.firebasestorage.app',
    measurementId: 'G-62SGFS0ME2',
  );

}